### PR TITLE
:sparkles: Implement Contracts!

### LINKED ISSUE #78: Functions should have contracts

### PR DESCRIPTION
**Pull request by iNoles**
Fixes #78

### CODE REVIEW

**Comment by kittinunf** [comment]
What are use-cases for these? Do you think we can have what is not possible before these contracts line added and what is possible after?

**Comment by iNoles** [comment]
> What are use-cases for these? Do you think we can have what is not possible before these contracts line added and what is possible after?

Here some details about it - https://www.baeldung.com/kotlin/contracts

**Comment by kittinunf** [comment]
I know but what I am trying to understand here is what exactly would the client be benefit by this, maybe some test code to show would be really awesome.

**Comment by kittinunf** [comment]
I have added some example here #108

**Review by kittinunf — APPROVED** [review]
Golden

**Pull request merged**
