### PR TITLE
[JS] Expand Result to support Kotlin/JS

### PR DESCRIPTION
**Pull request by kittinunf**
### What's in this PR?

This PR enables Result to support Kotlin/JS 🎉 🎉 🎉

### CODE REVIEW

**Comment by iNoles** [comment]
Module not found: Error: Can't resolve 'fs' in '/Users/runner/work/Result/Result/build/js/packages/Result-result-test/kotlin'

Module not found: Error: Can't resolve 'path' in '/Users/runner/work/Result/Result/build/js/packages/Result-result-test/kotlin'

**Comment by iNoles** [comment]
Error: ENOENT: no such file or directory, open './src/commonTest/resources/lorem_short.txt'
Error: ENOENT: no such file or directory, open './src/commonTest/resources/lorem_short.txt'

**Comment by kittinunf** [comment]
Hmm, I have no idea why this doesn't work 😢 ....

**Comment by iNoles** [comment]
> Hmm, I have no idea why this doesn't work 😢 ....

I found a way to fix it 

```
const val resource = "../../../../result/src/commonTest/resources"
```

**Review by iNoles — APPROVED** [review]
it is very good starts for now.

**Review by iNoles — APPROVED** [review]
Very awesome

**Pull request merged**
