### PR TITLE
Add getOrElse and any

### PR DESCRIPTION
**Pull request by prt2121**
Thanks for a nice framework. I just add two functions that might be useful. The idea is from other languages that have option/maybe apis. Also kinda align with Kotlin list apis. Anyway, just ignore it if it doesn't fit here.
Thanks again!

### CODE REVIEW

**Comment by kittinunf** [comment]
I like them both. Thanks for PR and thanks for contributing this. :sparkles:

**Comment by prt2121** [comment]
:thumbsup:

**Comment by kittinunf** [comment]
@prt2121, If you haven't noticed already, version 1.0.1 is out :)

**Comment by prt2121** [comment]
@kittinunf nice. thanks!

**Pull request merged**
