### PR TITLE
Change Exception to Throwable

### PR DESCRIPTION
**Pull request by seanghay**
Since Exception extends Throwable, I think the better way is to use Throwable over Exception for type and catching errors.

### Kotlin Standard Library

image

### Tweet
https://twitter.com/relizarov/status/1299248297849303040

### CODE REVIEW

**Comment by kittinunf** [comment]
@Globegitter what do you think about this though? If this is also something that we want to do I would love to do this for 4.0 version.

**Comment by bohsen** [comment]
This is good practice.

**Comment by R4md4c** [comment]
I doubt that's a good practice, as handling `Throwable` means you'd catch `Error` subclasses e.g. (OutOfMemoryError, VirtualMachineError or even AssertionError). I doubt that you'd want to catch an `OutOfMemoryError` since it points to an underlying problem in your code rather than a exception that you want to handle. 

Also imagine you're doing an assertion that throws an `AssertionError` and you're expecting the code to crash if that assertion is not met, but in that case it won't crash since it will be swallowed by the Result monad, which for sure won't be a good thing and will result in some potentially long debugging time.

**Comment by bohsen** [comment]
If this [kittinunf/Result](https://github.com/kittinunf/Result) at some point turns into a [multiplatform library](https://github.com/kittinunf/Result/issues/29) this change is needed and also usage in serverside software would be safer with this.

Personal opinion:
If you don't catch it you don't handle it. Rethrow it if you choose not to handle it, but at least try to somehow log it.
And also only catch an exception if you have an idea of what to do with it. Use `try-catch`/`runCatching` with care.

**Comment by Globegitter** [comment]
Not sure if this would have any implications for existing code but it does sound to me like a good fix @kittinunf :+1:

**Comment by kittinunf** [comment]
This should be superseded by #84

**Pull request closed without merging**
