### PR TITLE
:arrow_up: [4.0.0] Version 4.0.0

### PR DESCRIPTION
**Pull request by kittinunf**
### Description

This is to release the new version for Result v4.0.0.

- Thanks sooo much for all the effort made by @Globegitter #74, this indeed a great improvement on the library.

### CODE REVIEW

**Comment by Globegitter** [comment]
@kittinunf You also need to change the `artifactPublish` version in grade.properties - anything else that is blocking this from getting released?

**Comment by kittinunf** [comment]
Yes I have a question for you here https://github.com/kittinunf/Result/pull/73#issuecomment-757428082 what do you think?

**Comment by kittinunf** [comment]
I guess we will go ahead with 4.0.0 for now without any other changes then.

**Comment by kittinunf** [comment]
@Globegitter please approve if you have time :)

**Review by Globegitter — APPROVED** [review]
:+1:

**Comment by Globegitter** [comment]
@kittinunf I am not a 100% sure of the implications of using `Throwable` over `Exception`. It does sound like the more correct solution, but I would have to investigate first and would love to get this out as is. But what do you think?

**Comment by kittinunf** [comment]
Agree with you there! Let's merge this one first then if we seriously wanna migrate to `Throwable`, then we can do this later ✨

**Pull request merged**
