### PR TITLE
Implements ReadOnlyProperty to use as Delegates (`by`)

### PR DESCRIPTION
**Pull request by Shabinder**
**Note:** Edits from Maintainers is Allowed on this PR , in case needed ...

### CODE REVIEW

**Comment by kittinunf** [comment]
Hmm, I would love to hear how this is being used in practice? I would love to not add a feature just for the sake of having one.

**Comment by Shabinder** [comment]
@kittinunf For an example, Whenever I am operating on various results and Returning a new result using some custom logic , like as we do in flatmap etc , I need to access values , which I can do using **.get()** but personally in my opinion the readability can be increased by using delegaes ...

Present way: 
```
val res = result.get()
val res2 = result2.get()
.....and so on in our logic
```

Delegates way:
```
val res by result1
val res2 by result 3 
result 3 =  if (res ... custom logic && res2 ... custom logic) etc 
```

**Comment by kittinunf** [comment]
The reason why I reluctant to add this, how do you deal with `Failure` case? Using `get()` would basically throw exception in the delegates.

**Comment by Shabinder** [comment]
> The reason why I reluctant to add this, how do you deal with `Failure` case? Using `get()` would basically throw exception in the delegates.

it's just an alternate of using `get()` ,so I assume whenever someone using `delegate "by"` or `get()` , he/she is fully aware of the consequences if Result is Result.Failure , hence he/she is doing so in try catch block or in another Result.

If this behaviour raises a red flag then `get()` should do too, at the end it comes to the programmer how he/she is using it carefully

**Review by bohsen — COMMENTED** [review]
IMHO I don't see the use case for this and also the PR is missing tests that show how their use would improve the API.

It's mentioned that `get()` can get you into trouble. This is true. But `get()` has its use case covered (lazily getting your result). Merging this PR would make the use of the library unsafer I believe and would hide the "dangerous" behavior even more.

**Comment by Shabinder** [comment]
> IMHO I don't see the use case for this and also the PR is missing tests that show how their use would improve the API.
> 
> It's mentioned that `get()` can get you into trouble. This is true. But `get()` has its use case covered (lazily getting your result). Merging this PR would make the use of the library unsafer I believe and would hide the "dangerous" behavior even more.

I see what you are saying, this PR **never focussed on covering more use cases**, instead, it was made to adapt to more code writing styles where programmers know what they are doing and are aware of the consequences like as using `get() or by` can **throw exceptions if Result is Result.Failed**

I still dont understand that why are we afraid that it may or may not hide the _dangerous_ behaviour,  as the same functionality is already there, it just brings a different way to access it _(which I guess is the reason you say it will make library more unsafer, right?)_

but I believe this will make the library `more unsafer` for only those who tend to forget what their code's behaviour is and what it can result to...

If I interpreted your message wrong , feel free to correct me :smile:

**Comment by bohsen** [comment]
I get the point about supporting developers code style and as a side note I really love how delegates work in kotlin. I just think people tend to forget the risk of adding things to an API without thinking about the burden of maintenance. This PR could easily end up as one of those cases if added. Especially as long as the API isn't documented and you have to rely on people reading and more importantly understanding your code. This is IMO when you need to take a close look at the use case of something.

**Comment by kittinunf** [comment]
@bohsen Thanks for your opinion, I quite agree with you.

@Shabinder while I understand where you are coming from, unfortunately, I don't feel this would improve the usage of the library. While it is true that this behaves like `get()`, but `get()` is more explicit and clear when it throws. Meanwhile, the usage of the delegate would shadow the real "get()" implementation. 

Thanks for your contribution but I don't quite see this as something that we would love to make it into the library. As I am trying to trimming down the non-common usage to support KMM in https://github.com/kittinunf/Result/pull/84, I would go and favor the simpler route than provide multiple ways of getting the value.

**Comment by Shabinder** [comment]
I understand your decision, hence will be closing this.

**Pull request closed without merging**
