### PR TITLE
Update Kotlin version to 1.6.20

### PR DESCRIPTION
**Pull request by matiascalvo**
The objective of this PR is to update Kotlin to 1.6.20

Tasks:
- Update [TOML file](https://github.com/kittinunf/Result/blob/master/gradle/libs.versions.toml)
- Update README
- Run tests successfully

### CODE REVIEW

**Comment by matiascalvo** [comment]
@kittinunf would you review this PR?

**Comment by kittinunf** [comment]
Sure! Thanks for this.

**Review by iNoles — CHANGES_REQUESTED** [review]
Since 1.6.20 released, I think you should change PR to it.

**Comment by matiascalvo** [comment]
@iNoles the aim of this PR was to sync the current version of the Kotlin version in the [Readme](https://github.com/kittinunf/Result/blob/master/README.md) (1.5.20) file with the one in the [catalog file](https://github.com/kittinunf/Result/blob/master/gradle/libs.versions.toml) (1.6.10).

Do you suggest upgrading both to 1.6.20 in this PR?

**Comment by iNoles** [comment]
> @iNoles the aim of this PR was to sync the current version of the Kotlin version in the [Readme](https://github.com/kittinunf/Result/blob/master/README.md) (1.5.20) file with the one in the [catalog file](https://github.com/kittinunf/Result/blob/master/gradle/libs.versions.toml) (1.6.10).
> 
> Do you suggest upgrading both to 1.6.20 in this PR?

Yeah

**Comment by matiascalvo** [comment]
Done, also updated PR title & description

**Review by iNoles — APPROVED** [review]

**Pull request merged**
