### PR TITLE
Add Kotlin's coroutines support

### PR DESCRIPTION
**Pull request by kittinunf**
### What's in this PR?

This is to add coroutine support. It was originally created by @tudorgk so I will blatantly just make it as another module for coroutine support. All credit goes to him 🍺 👍 :). I just update project and add necessary module.

Merging this will close #28.

### CODE REVIEW

**Comment by kittinunf** [comment]
@tudorgk I will try to merge this unless you have an objection. Really sorry for dragging this too long though. 🙏

**Comment by tudorgk** [comment]
I'm sorry because I was caught up with other stuff and forgot about the PR completely 😅. Also, objectively speaking, I don't think there's a way to abstract away the coroutine support even more because kotlin's implementation is rooted deep into the language itself (the `suspend` keyword for example)

**Comment by kittinunf** [comment]
@tudorgk No worries. Let me merge this then :)

**Comment by bohsen** [comment]
Just wanted to say really great work to you guys. Having this in the library will be SO good. 

This also closes #27

**Pull request merged**
